#!/bin/bash
# Verify that all files have been created
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   JEE RANK PREDICTOR - PROJECT COMPLETION VERIFICATION        ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Count files
echo "📊 File Count:"
echo "   Frontend:        $(find frontend -type f | wc -l) files"
echo "   Backend:         $(find backend -type f 2>/dev/null | grep -v __pycache__ | wc -l) files"
echo "   Scripts:         $(find scripts -type f | wc -l) files"
echo "   Configuration:   $(find . -maxdepth 1 -type f | grep -E '\.(txt|yaml|bat|sh)$' | wc -l) files"
echo "   Documentation:   $(find . -maxdepth 1 -type f -name '*.md' | wc -l) files"
echo ""

# Check individual files
echo "✅ Core Files:"
echo ""
echo "   Frontend:"
[ -f "frontend/index.html" ] && echo "      ✅ frontend/index.html" || echo "      ❌ frontend/index.html"
[ -f "frontend/style.css" ] && echo "      ✅ frontend/style.css" || echo "      ❌ frontend/style.css"
[ -f "frontend/app.js" ] && echo "      ✅ frontend/app.js" || echo "      ❌ frontend/app.js"
echo ""

echo "   Backend:"
[ -f "backend/main.py" ] && echo "      ✅ backend/main.py" || echo "      ❌ backend/main.py"
[ -f "backend/predictor.py" ] && echo "      ✅ backend/predictor.py" || echo "      ❌ backend/predictor.py"
[ -f "backend/rank_formula.py" ] && echo "      ✅ backend/rank_formula.py" || echo "      ❌ backend/rank_formula.py"
[ -f "backend/data_loader.py" ] && echo "      ✅ backend/data_loader.py" || echo "      ❌ backend/data_loader.py"
echo ""

echo "   Scripts:"
[ -f "scripts/download_data.py" ] && echo "      ✅ scripts/download_data.py" || echo "      ❌ scripts/download_data.py"
[ -f "scripts/validate_data.py" ] && echo "      ✅ scripts/validate_data.py" || echo "      ❌ scripts/validate_data.py"
[ -f "scripts/train_model.py" ] && echo "      ✅ scripts/train_model.py" || echo "      ❌ scripts/train_model.py"
echo ""

echo "   Configuration:"
[ -f "requirements.txt" ] && echo "      ✅ requirements.txt" || echo "      ❌ requirements.txt"
[ -f "render.yaml" ] && echo "      ✅ render.yaml" || echo "      ❌ render.yaml"
[ -f ".gitignore" ] && echo "      ✅ .gitignore" || echo "      ❌ .gitignore"
echo ""

echo "   Setup Scripts:"
[ -f "setup.sh" ] && echo "      ✅ setup.sh" || echo "      ❌ setup.sh"
[ -f "setup.bat" ] && echo "      ✅ setup.bat" || echo "      ❌ setup.bat"
echo ""

echo "   Documentation:"
[ -f "README.md" ] && echo "      ✅ README.md" || echo "      ❌ README.md"
[ -f "PROJECT_SUMMARY.md" ] && echo "      ✅ PROJECT_SUMMARY.md" || echo "      ❌ PROJECT_SUMMARY.md"
[ -f "QUICK_REFERENCE.md" ] && echo "      ✅ QUICK_REFERENCE.md" || echo "      ❌ QUICK_REFERENCE.md"
[ -f "SETUP_COMPLETE.txt" ] && echo "      ✅ SETUP_COMPLETE.txt" || echo "      ❌ SETUP_COMPLETE.txt"
echo ""

echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎉 PROJECT COMPLETE!"
echo ""
echo "📝 Total files created: 19"
echo ""
echo "Next steps:"
echo "1. Run: bash setup.sh (macOS/Linux) or setup.bat (Windows)"
echo "2. Or manually:"
echo "   • python -m venv venv && source venv/bin/activate"
echo "   • pip install -r requirements.txt"
echo "   • python scripts/download_data.py --synthetic"
echo "   • python scripts/train_model.py"
echo "   • uvicorn backend.main:app --reload"
echo "3. Open: http://localhost:8001 (in separate terminal: cd frontend && python -m http.server 8001)"
echo ""
echo "For detailed info, see README.md"
echo ""
